services:
  - type: web
    name: arc-pdf-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: ENV
        value: production
      - key: DEBUG
        value: false
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: CORS_ORIGINS
        sync: false
