services:
  - type: web
    name: arc-pdf-api
    env: python
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: ENV
        value: production
      - key: DEBUG
        value: false
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: CORS_ORIGINS
        sync: false
